### ISSUE TITLE
Running app and app is crashing in starting

### ISSUE THREAD

**Issue by GrishmaPromact** [Fotoapparat/Fotoapparat#146] opened 2017-12-07 04:40 UTC
I am running this app and app is crashed in starting.
Please do needful.
I have attached screenshot of crash log.
![crash](https://user-images.githubusercontent.com/20226076/33699074-db1ba8b0-db36-11e7-9504-56af03dffb47.png)

**Comment by Diolor** [comment] 2017-12-07 08:54
Will be fixed by #145

**Comment by GrishmaPromact** [comment] 2017-12-07 09:03
@Diolor ohk. Thanks.

**Comment by GrishmaPromact** [comment] 2017-12-11 05:35
@Diolor Still crashing is occurred. When your PR is getting merged?

**Comment by GrishmaPromact** [comment] 2017-12-20 07:07
@Diolor when it going to resolved? We have higher priority to add this library in project but because of this issue, we are not able to add that.

**Comment by Diolor** [comment] 2017-12-20 10:47
This will be fixed in 2.0. You can use `2.0.0-beta1`, if you want to, which has the fix. Be warry: apis and camera behavior might change. See `v2` branch for more details and how-to configure v2 FA.

**Comment by GrishmaPromact** [comment] 2017-12-20 11:35
v2 update - App crashed while change the mobile to portrait to landscape continuously .
I attached the screen shot of crashed log.
![image](https://user-images.githubusercontent.com/20226076/34205365-0589b972-e5a8-11e7-806d-af47663548cf.png)

**Comment by Diolor** [comment] 2017-12-24 12:57
This has been fixed in `2.0.0-beta1` and I cannot reproduce it further on a pixel 2 XL

**Comment by GrishmaPromact** [comment] 2017-12-26 04:59
I have used Samsung galaxy on 5 (Crashed while change the orientation continuously) and also Moto e4 plus (In this camera is not displaying only blank white screen is displaying and crashed while i am zooming camera).

**Closed** 2017-12-31 16:08 UTC
Labels: bug
