### ISSUE TITLE
Front Camera Issue (Not Capturing)

### ISSUE THREAD

**Issue by shivam2702** [Fotoapparat/Fotoapparat#3] opened 2017-04-24 11:45 UTC
In some devices i faced an issue that its not capturing the Photo by the front camera. 

Ex: One Plus 2 etc...

Sorry for no logs as its not showing any.

**Comment by Diolor** [comment] 2017-04-24 13:01
Hi @shivam2702, was it API 21+ ? 
Also did any of the following was the case: rotate the activity, had another take request before, or low light?

**Comment by shivam2702** [comment] 2017-04-24 13:06
API Level was 23 (Android M)
No everything was fine best light first request and portrait.

**Comment by dmitry-zaitsev** [comment] 2017-04-24 22:02
We are able to reproduce the issue. Fix will come soon.

**Comment by Diolor** [comment] 2017-05-01 22:22
This issue is now fixed 👍

**Comment by shivam2702** [comment] 2017-05-03 05:16
Thanks 🥇  you are awesome....

**Comment by dmitry-zaitsev** [comment] 2017-05-09 19:12
Still an issue for Samsung S7 Edge. Did not try on Moto G3 yet.

**Comment by Diolor** [comment] 2017-05-09 21:19
Default FA configuration in sample app? Sorry cannot reproduce in my 6P

**Comment by dmitry-zaitsev** [comment] 2017-05-09 21:50
@Diolor issue is in `ImageCaptureAction#getPhoto` - for some reason `countDownLatch` is never actually counted down. I suspect that it might be because image becomes available before listener is registered and therefore `onImageAvailable` is not called.

**Comment by dmitry-zaitsev** [comment] 2017-05-09 22:09
Fixed now.

**Closed by dmitry-zaitsev** 2017-05-09 22:09 UTC
Labels: bug
